header:
    version: 11
distro: kapernikov
build_system: oe
machine: qemux86-64
target: image-kapernikov
#local_conf_header:
#  meta-custom: |
#    BB_ALLOWED_NETWORKS="github.com"


repos:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    branch: "scarthgap"
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded"
    branch: "scarthgap"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-filesystems:
  meta-virtualization:
    url: "https://git.yoctoproject.org/git/meta-virtualization"
    branch: "scarthgap"
    layers:
      ../meta-virtualization:
  meta-security:
    url: "https://git.yoctoproject.org/git/meta-security"
    branch: "scarthgap"
    layers:
      ../meta-security:
  meta-swupdate:
    url: "https://github.com/sbabic/meta-swupdate"
    branch: "scarthgap"
    layers:
      ../meta-swupdate:
  meta-kapernikov:
    path: "./meta-kapernikov/"
